# apiVersion: v1
# kind: Service
# metadata:
#   name: ai-mini-service
# spec:
#   selector:
#     app: ai-mini
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: ai-mini-service
spec:
  selector:
    app: ai-lab-final-mini-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort